#!/usr/bin/env python3
"""Generates every Maestro application icon from one geometry definition.

The mark is an M drawn as a single continuous round-capped stroke — the path a
baton traces through a bar — on a tile whose gradient runs between two colours
taken from the application's own dark scheme in `lib/app/maestro_theme.dart`.
Keeping the geometry here rather than in the binaries means the SVG and the ICO
can never drift apart, and a change is a diff rather than a replaced blob.

Outputs, all regenerated in place:

    windows/runner/resources/app_icon.ico   Windows executable and taskbar icon
    tooling/packaging/maestro.svg           Linux scalable icon (deb, AppImage)
    tooling/packaging/icons/maestro-N.png   Linux hicolor sizes and the MSIX logo

Run from the repository root:

    python3 tooling/packaging/icons/generate_icons.py

Requires Pillow. Nothing in CI runs this: icons change by hand, and the
generated files are committed so a build never depends on Python.
"""

from __future__ import annotations

import struct
import sys
from pathlib import Path

try:
    from PIL import Image, ImageDraw
except ImportError:  # pragma: no cover - developer tooling
    sys.exit('Pillow is required: pip install Pillow')

# ---------------------------------------------------------------- geometry --

GRID = 128
SUPERSAMPLE = 8
CORNER_RADIUS = 27

# The baton's path through the bar, which is also an M: down, up, down, up.
MARK_POINTS = [(29, 95), (29, 34), (64, 84), (99, 34), (99, 95)]
MARK_WIDTH = 15

# From the application's dark colour scheme, so the icon and the product agree.
GROUND_TOP = (0x25, 0x31, 0x69)  # blended toward dark primaryContainer
GROUND_BOTTOM = (0x11, 0x13, 0x18)  # dark surface
MARK = (0xB9, 0xC3, 0xFF)  # dark primary, the same accent the terminal uses

# 16 and 24 are the sizes Windows actually shows in a taskbar and a title bar;
# 256 is what the shell scales from. The rest are the hicolor conventions.
ICO_SIZES = (16, 24, 32, 48, 64, 128, 256)
# 1024 is the MSIX source: the packager scales a single logo up to 2480px
# wide, so it wants the largest square we can honestly give it.
PNG_SIZES = (16, 24, 32, 48, 64, 128, 256, 512, 1024)

# ----------------------------------------------------------------- drawing --


def _lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def _stroke(draw: ImageDraw.ImageDraw, points, width: float, fill) -> None:
    """A round-capped, round-joined stroke, stamped rather than polylined.

    `ImageDraw.line(joint="curve")` leaves serrated spikes where segments meet;
    stamping overlapping discs along the path cannot.
    """
    radius = width * SUPERSAMPLE / 2
    previous = None
    for x, y in points:
        px, py = x * SUPERSAMPLE, y * SUPERSAMPLE
        if previous is not None:
            dx, dy = px - previous[0], py - previous[1]
            span = max(abs(dx), abs(dy))
            for step in range(1, int(span) + 1):
                t = step / span
                cx, cy = previous[0] + dx * t, previous[1] + dy * t
                draw.ellipse(
                    [cx - radius, cy - radius, cx + radius, cy + radius], fill=fill
                )
        draw.ellipse([px - radius, py - radius, px + radius, py + radius], fill=fill)
        previous = (px, py)


def _ground(size: int) -> Image.Image:
    """The rounded tile the mark sits on."""
    column = Image.new('RGB', (1, size))
    pixels = column.load()
    for y in range(size):
        t = y / (size - 1)
        pixels[0, y] = tuple(
            int(round(_lerp(GROUND_TOP[i], GROUND_BOTTOM[i], t))) for i in range(3)
        )
    base = column.resize((size, size), Image.Resampling.BICUBIC).convert('RGBA')
    mask = Image.new('L', (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, size - 1, size - 1],
        radius=int(round(CORNER_RADIUS * SUPERSAMPLE)),
        fill=255,
    )
    tile = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    tile.paste(base, (0, 0), mask)
    return tile


def render_full() -> Image.Image:
    image = _ground(GRID * SUPERSAMPLE)
    _stroke(ImageDraw.Draw(image), MARK_POINTS, MARK_WIDTH, MARK + (0xFF,))
    return image


def render(full: Image.Image, size: int) -> Image.Image:
    return full.resize((size, size), Image.Resampling.LANCZOS)


# ------------------------------------------------------------------ output --


def _hex(colour) -> str:
    return '#%02X%02X%02X' % colour


def write_svg(path: Path) -> None:
    """The scalable icon, carrying the same geometry as the rasters."""
    points = ' '.join(f'{x} {y}' for x, y in MARK_POINTS)
    path.write_text(
        f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {GRID} {GRID}"
     width="{GRID}" height="{GRID}" role="img" aria-label="Maestro">
  <!-- Generated by tooling/packaging/icons/generate_icons.py. Edit the
       geometry there so the SVG and the Windows icon stay identical. -->
  <defs>
    <linearGradient id="ground" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{_hex(GROUND_TOP)}"/>
      <stop offset="1" stop-color="{_hex(GROUND_BOTTOM)}"/>
    </linearGradient>
  </defs>
  <rect width="{GRID}" height="{GRID}" rx="{CORNER_RADIUS}" fill="url(#ground)"/>
  <polyline points="{points}" fill="none" stroke="{_hex(MARK)}"
            stroke-width="{MARK_WIDTH}" stroke-linecap="round"
            stroke-linejoin="round"/>
</svg>
''',
        encoding='utf-8',
    )


def write_ico(path: Path, full: Image.Image) -> None:
    """A multi-size ICO: BMP entries for the small sizes, PNG for 256.

    Pillow's own ICO writer downsamples from a single image with its default
    filter; rendering each size from the full-resolution mark keeps the small
    ones crisp, which is the whole point of shipping them.
    """
    entries = []
    for size in sorted(ICO_SIZES):
        image = render(full, size)
        if size >= 256:
            from io import BytesIO

            buffer = BytesIO()
            image.save(buffer, format='PNG')
            entries.append((size, buffer.getvalue()))
        else:
            entries.append((size, _dib(image)))

    header = struct.pack('<HHH', 0, 1, len(entries))
    offset = len(header) + 16 * len(entries)
    directory, payload = b'', b''
    for size, data in entries:
        directory += struct.pack(
            '<BBBBHHII',
            0 if size >= 256 else size,
            0 if size >= 256 else size,
            0,
            0,
            1,
            32,
            len(data),
            offset,
        )
        payload += data
        offset += len(data)
    path.write_bytes(header + directory + payload)


def _dib(image: Image.Image) -> bytes:
    """A 32-bit bottom-up DIB with the AND mask an ICO entry expects."""
    width, height = image.size
    pixels = image.convert('RGBA').load()
    rows = []
    for y in range(height - 1, -1, -1):
        row = bytearray()
        for x in range(width):
            r, g, b, a = pixels[x, y]
            row += bytes((b, g, r, a))
        rows.append(bytes(row))
    colour = b''.join(rows)

    # The AND mask is unused for 32-bit icons but must still be present and
    # padded to a 4-byte boundary per row.
    stride = ((width + 31) // 32) * 4
    mask = b''.join(b'\x00' * stride for _ in range(height))

    header = struct.pack(
        '<IiiHHIIiiII',
        40,
        width,
        height * 2,  # colour rows plus mask rows
        1,
        32,
        0,
        len(colour) + len(mask),
        0,
        0,
        0,
        0,
    )
    return header + colour + mask


def main() -> int:
    root = Path(__file__).resolve().parents[3]
    icons = root / 'tooling' / 'packaging' / 'icons'
    icons.mkdir(parents=True, exist_ok=True)

    full = render_full()
    write_svg(root / 'tooling' / 'packaging' / 'maestro.svg')
    write_ico(root / 'windows' / 'runner' / 'resources' / 'app_icon.ico', full)
    for size in PNG_SIZES:
        render(full, size).save(icons / f'maestro-{size}.png')

    print(f'icons: wrote svg, ico ({len(ICO_SIZES)} sizes), {len(PNG_SIZES)} pngs')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
